### PR TITLE
Add Elm language

### PR DESCRIPTION
**Pull request by sevillaarvin**
Add commonmarker as dependency for parsing markdown

If you’re adding a new scraper, please ensure that you have:

- [x] Tested the scraper on a local copy of DevDocs
- [x] Ensured that the docs are styled similarly to other docs on DevDocs

- [x] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [x] `16.png`: a 16×16 pixel icon for the doc
  - [x] `16@2x.png`: a 32×32 pixel icon for the doc
  - [x] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

### CODE REVIEW

**Comment by Violet-Bora-Lee** [comment]
Could you update the status of Trello?

https://trello.com/b/6BmTulfx/devdocs-documentation

**Comment by sevillaarvin** [comment]
> Could you update the status of Trello?
> 
> https://trello.com/b/6BmTulfx/devdocs-documentation

Not sure what you meant, so I tried moving the card from `To Do` to `Pull Request Opened`, but I couldn't because the context menu is not showing.

image

**Comment by alejandrociatti** [comment]
was this closed due to inactivity @simon04 ? 
Or does it not work?  
I'm willing to address the requested changes if it is just that

**Comment by simon04** [comment]
Yeah, this PR was closed due to inactivity. Feel free to pick-up and resurrect this PR. Thanks!

**Pull request closed without merging**
