### PR TITLE
Update Nim documentation (1.0.0)

### PR DESCRIPTION
**Pull request by Br1ght0ne**
- [X] Updated the versions and releases in the scraper file
- [X] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [X] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [X] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [ ] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

---

Currently emits an error on a single page:

```
ERROR:
  https://nim-lang.org/docs/strutils.html
  ArgumentError: invalid byte sequence in UTF-8
```

Everything else is good.

---
This change is [Reviewable](https://reviewable.io/reviews/freecodecamp/devdocs/1089)

### CODE REVIEW

**Comment by ArMour85** [comment]
Hello,
Can nobody resolves this issues to finish the PR ?

**Comment by Clonkk** [comment]
Any news on this ? Current version is 1.2.0, it would be nice to have an up to date devdocs for Nim.

**Comment by scherepn** [comment]
An updated version of Nim was added in PR #1407

**Comment by MasterEnoc** [comment]
This PR should be closed, nim is currently up to date.

**Pull request closed without merging**
