### PR TITLE
Migrate CoffeeScript to JavaScript

### LINKED ISSUE #1197: Migration from CoffeeScript

### PR DESCRIPTION
**Pull request by simon04**
I'm migrating one after another CoffeeScript file to JavaScript using https://decaffeinate-project.org/repl/.

Fixes #1197.

### CODE REVIEW

**Comment by JuanVqz** [comment]
do you want help with this?

**Comment by simon04** [comment]
> do you want help with this?

Help is welcome, I'm not actively working on this at the moment.

> how are you converting coffee files to javascript?

See https://github.com/freeCodeCamp/devdocs/pull/1441#issue-773998150

**Comment by simon04** [comment]
Migration seems to be successful. Let's give it a try. I'll keep an eye on https://devdocs.sentry.io/issues/ to spot and fix potential bugs...

**Comment by ojeytonwilliams** [comment]
Sentry seems pretty calm. Nice work, @simon04!

**Pull request merged**
