### PR TITLE
Add Julia version 1.5.3

### PR DESCRIPTION
**Pull request by MasterEnoc**
- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by scherepn** [comment]
The Julia docs are fairly small (<5MB), it should be easy to add Version 1.3 and 1.4 of the documentation too.

**Comment by MasterEnoc** [comment]
Version 1.4 and 1.3 added. Thank you for your suggestion @scherepn

**Comment by simon04** [comment]
For Julia 1.4 (only), some headings got lost:

**Comment by scherepn** [comment]
The docs HTML structure changed starting w/ 1.4.

I think the full 'correct' way to solve this is to create a new cleaner filter specifically for 1.4+ versions so future maintainers can keep them separate. The pages are substantially similar though, so cheating is probably fine.

https://github.com/scherepn/devdocs/commit/17cbea7d4eea8fe3fb5cdde799ea3a1a4ab53893

**Review by simon04 — APPROVED** [review]
Thank you!

**Pull request merged**
