### PR TITLE
Add docker compose file for easier development

### PR DESCRIPTION
**Pull request by brpaz**
This PR adds a "docker-compose" file to facilitate the development using Docker.

### CODE REVIEW

**Comment by jmerle** [comment]
LGTM for production usage.

For development usage, I see two improvements that can be made:
- There's no need to download all docs in development.
- Documentation on how to run commands inside the container can be helpful to newcomers (especially since the DevDocs cli is used quite a lot when adding/fixing documentation).

**Comment by brpaz** [comment]
The main idea was for development usage. In production, you wouldn't mount the volumes that way but use the data that is inside the image.

Yes I agree with your points. Downloading all the documentation took a while.

I just build this in 5 minutes as I am trying to see how to create new Documentation. Will see how can I improve the mentioned points.

**Comment by jmerle** [comment]
Are you still planning on updating the PR, or is it okay with you to close this for now?

**Comment by jmerle** [comment]
I'm closing this PR for now. Feel free to create a new one if you decide to start working on this again.

**Pull request closed without merging**
