### PR TITLE
Added Eigen3 document

### PR DESCRIPTION
**Pull request by xjkdev**
If you’re adding a new scraper, please ensure that you have:

- [X] Tested the scraper on a local copy of DevDocs
- [X] Ensured that the docs are styled similarly to other docs on DevDocs

- [X] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [X] `16.png`: a 16×16 pixel icon for the doc
  - [X] `16@2x.png`: a 32×32 pixel icon for the doc
  - [X] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

### CODE REVIEW

**Comment by xjkdev** [comment]
Known issue: doc icon look a little ugly in dark theme.

**Review by simon04 — CHANGES_REQUESTED** [review]
The resulting page looks bad in the devdocs dark mode: 
Screenshot 2022-03-09 at 19-38-55 Eigen3 documentation — DevDocs


Code fragments should make use of devdocs's code highlighting: remove all markup and put the verbatim code in a `<pre data-language="...">` block.

Almost all other CSS classes should be removed / rewritten to devdocs standard. Having 268 lines in assets/stylesheets/pages/_eigen3.scss is fishy.

The scraper generates a bunch of warnings and exceptions:

<details>
```
/Users/simon/src/devdocs/lib/docs/filters/eigen3/entries.rb:93: warning: found `= literal' in conditional, should be ==
Skipped broken image (): https://eigen.tuxfamily.org/dox/Tutorial_sparse_example.jpeg                                                                     
ERROR:                                                                                                                                                    
  https://eigen.tuxfamily.org/dox/group__Splines__Module.html
  Docs::Entry::Invalid: missing type

  /Users/simon/src/devdocs/lib/docs/core/models/entry.rb:17:in `initialize'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `new'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `build_entry'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:53:in `block in build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `map'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:14:in `entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:6:in `call'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:179:in `process_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:160:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:159:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:77:in `block in build_pages'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:59:in `block (2 levels) in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `each'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:57:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:18:in `run'
  /Users/simon/src/devdocs/lib/docs/core/scrapers/url_scraper.rb:38:in `request_all'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:76:in `build_pages'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:108:in `block in store_pages'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:107:in `store_pages'
  /Users/simon/src/devdocs/lib/docs.rb:100:in `generate'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:303:in `generate_doc'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:105:in `generate'

ERROR:                                                                                                                                                    
  https://eigen.tuxfamily.org/dox/TopicScalarTypes.html
  Docs::Entry::Invalid: missing type

  /Users/simon/src/devdocs/lib/docs/core/models/entry.rb:17:in `initialize'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `new'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `build_entry'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:53:in `block in build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `map'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:14:in `entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:6:in `call'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:179:in `process_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:160:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:159:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:77:in `block in build_pages'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:59:in `block (2 levels) in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `each'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:57:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:18:in `run'
  /Users/simon/src/devdocs/lib/docs/core/scrapers/url_scraper.rb:38:in `request_all'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:76:in `build_pages'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:108:in `block in store_pages'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:107:in `store_pages'
  /Users/simon/src/devdocs/lib/docs.rb:100:in `generate'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:303:in `generate_doc'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:105:in `generate'

Skipped large image (316 KB): https://eigen.tuxfamily.org/dox/structEigen_1_1EigenBase__inherit__graph.png                                                
ERROR:                                                                                                                                                    
  https://eigen.tuxfamily.org/dox/TopicResizing.html
  Docs::Entry::Invalid: missing type

  /Users/simon/src/devdocs/lib/docs/core/models/entry.rb:17:in `initialize'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `new'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `build_entry'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:53:in `block in build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `map'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:14:in `entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:6:in `call'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:179:in `process_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:160:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:159:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:77:in `block in build_pages'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:59:in `block (2 levels) in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `each'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:57:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:18:in `run'
  /Users/simon/src/devdocs/lib/docs/core/scrapers/url_scraper.rb:38:in `request_all'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:76:in `build_pages'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:108:in `block in store_pages'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:107:in `store_pages'
  /Users/simon/src/devdocs/lib/docs.rb:100:in `generate'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:303:in `generate_doc'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:105:in `generate'

ERROR:                                                                                                                                                    
  https://eigen.tuxfamily.org/dox/TopicVectorization.html
  Docs::Entry::Invalid: missing type

  /Users/simon/src/devdocs/lib/docs/core/models/entry.rb:17:in `initialize'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `new'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `build_entry'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:53:in `block in build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `map'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:14:in `entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:6:in `call'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:179:in `process_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:160:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:159:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:77:in `block in build_pages'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:59:in `block (2 levels) in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `each'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:57:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:18:in `run'
  /Users/simon/src/devdocs/lib/docs/core/scrapers/url_scraper.rb:38:in `request_all'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:76:in `build_pages'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:108:in `block in store_pages'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:107:in `store_pages'
  /Users/simon/src/devdocs/lib/docs.rb:100:in `generate'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:303:in `generate_doc'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:105:in `generate'

ERROR:                                                                                                                                                    
  https://eigen.tuxfamily.org/dox/TopicEigenExpressionTemplates.html
  Docs::Entry::Invalid: missing type

  /Users/simon/src/devdocs/lib/docs/core/models/entry.rb:17:in `initialize'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `new'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:60:in `build_entry'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:53:in `block in build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `map'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:52:in `build_entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:14:in `entries'
  /Users/simon/src/devdocs/lib/docs/filters/core/entries.rb:6:in `call'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:179:in `process_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:160:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:159:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:77:in `block in build_pages'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:59:in `block (2 levels) in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `each'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:58:in `block in handle_response'
  /Users/simon/src/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:57:in `handle_response'
  /Users/simon/src/devdocs/lib/docs/core/requester.rb:18:in `run'
  /Users/simon/src/devdocs/lib/docs/core/scrapers/url_scraper.rb:38:in `request_all'
  /Users/simon/src/devdocs/lib/docs/core/scraper.rb:76:in `build_pages'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:108:in `block in store_pages'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /Users/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /Users/simon/src/devdocs/lib/docs/core/doc.rb:107:in `store_pages'
  /Users/simon/src/devdocs/lib/docs.rb:100:in `generate'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:303:in `generate_doc'
  /Users/simon/src/devdocs/lib/tasks/docs.thor:105:in `generate'

Skipped large image (138 KB): https://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase__inherit__graph.png                                           
Skipped broken image (): https://eigen.tuxfamily.org/dox/classEigen_1_1SVDBase__inherit__graph.png                                                        
Skipped broken image (): https://eigen.tuxfamily.org/dox/classEigen_1_1symbolic_1_1SymbolExpr__inherit__graph.png                                         
```

</details>

**Comment by xjkdev** [comment]
> The scraper generates a bunch of warnings and exceptions

There are some empty or invalid pages in the docs that can be accessed. I don't know how to filter them out based on the content, so I return nil in get_type. This works out, however, make it throws exceptions. Is there a better way to filter them out @simon04?

**Comment by xjkdev** [comment]
I have replaced code fragment by `<pre>`, however, indents more than one spaces are eaten by Nokogiri because the original code fragment is not wrap in `pre` but `div`.  Is there a way to prevent this?

original doc and after processing:

截屏2022-03-10 下午5 22 09

**Comment by simon04** [comment]
> I have replaced code fragment by `\<pre\>`, however, indents more than one spaces are eaten by Nokogiri because the original code fragment is not wrap in `pre` but `div`. Is there a way to prevent this?

Take a look at https://github.com/freeCodeCamp/devdocs/blob/c6c332c93b4cb31c3c4dfa100de5d68116a2b6b6/lib/docs/scrapers/go.rb#L43-L46 and https://github.com/freeCodeCamp/devdocs/blob/c6c332c93b4cb31c3c4dfa100de5d68116a2b6b6/lib/docs/scrapers/pug.rb#L31-L35

**Comment by xjkdev** [comment]
Thanks. and now all errors are cleared.

**Review by simon04 — APPROVED** [review]
Thank you!

**Pull request merged**
