### PR TITLE
Update Laravel Docs

### PR DESCRIPTION
**Pull request by Jamesking56**
If you're updating an existing documentation to it's latest version, please ensure that you have:

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [ ] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by Jamesking56** [comment]
For some reason, I'm getting some errors locally when trying to build 5.8 and 6.0 docs. I think its being caused by the new Laravel website design but not sure how else I can fix it.

**Comment by Anspagespace** [comment]
From f21bc1c0d98c4de86627f42b2ee9cee94c9d3d95 Mon Sep 17 00:00:00 2001
From: James King <james@jamesking56.uk>
Date: Sun, 8 Sep 2019 15:29:10 -0700
Subject: [PATCH 1/6] Add Laravel 5.8 documentation

---
 lib/docs/scrapers/laravel.rb | 13 +++++++++++++
 1 file changed, 13 insertions(+)

diff --git a/lib/docs/scrapers/laravel.rb b/lib/docs/scrapers/laravel.rb
index e45b0bed1..c030d30c7 100644
--- a/lib/docs/scrapers/laravel.rb
+++ b/lib/docs/scrapers/laravel.rb
@@ -29,6 +29,19 @@ class Laravel < UrlScraper
       Laravel is a trademark of Taylor Otwell.
     HTML
 
+    version '5.8' do
+      self.release = '5.8.35'
+      self.root_path = '/api/5.8/index.html'
+      self.initial_paths = %w(/docs/5.8/installation /api/5.8/classes.html)
+
+      options[:only_patterns] = [%r{\A/api/5\.8/}, %r{\A/docs/5\.8/}]
+
+      options[:fix_urls] = ->(url) do
+        url.sub! %r{#{Regexp.escape(Laravel.base_url)}/docs\/(?!\d)}, "#{Laravel.base_url}/docs/5.8/"
+        url
+      end
+    end
+
     version '5.7' do
       self.release = '5.7.7'
       self.root_path = '/api/5.7/index.html'

From bfe0a9be47197762214186841aefc068f8710f4d Mon Sep 17 00:00:00 2001
From: James King <james@jamesking56.uk>
Date: Sun, 8 Sep 2019 15:31:11 -0700
Subject: [PATCH 2/6] Add Laravel 6.0 documentation

---
 lib/docs/scrapers/laravel.rb | 13 +++++++++++++
 1 file changed, 13 insertions(+)

diff --git a/lib/docs/scrapers/laravel.rb b/lib/docs/scrapers/laravel.rb
index c030d30c7..52997e06d 100644
--- a/lib/docs/scrapers/laravel.rb
+++ b/lib/docs/scrapers/laravel.rb
@@ -29,6 +29,19 @@ class Laravel < UrlScraper
       Laravel is a trademark of Taylor Otwell.
     HTML
 
+    version '6.0' do
+      self.release = '6.0.1'
+      self.root_path = '/api/6.x/index.html'
+      self.initial_paths = %w(/docs/6.0/installation /api/6.x/classes.html)
+
+      options[:only_patterns] = [%r{\A/api/6\.x/}, %r{\A/docs/6\.0/}]
+
+      options[:fix_urls] = ->(url) do
+        url.sub! %r{#{Regexp.escape(Laravel.base_url)}/docs\/(?!\d)}, "#{Laravel.base_url}/docs/6.0/"
+        url
+      end
+    end
+
     version '5.8' do
       self.release = '5.8.35'
       self.root_path = '/api/5.8/index.html'

From 7a4343b5451d91d7c048417fdb3f46e4935269bb Mon Sep 17 00:00:00 2001
From: James King <james@jamesking56.uk>
Date: Sun, 8 Sep 2019 15:36:48 -0700
Subject: [PATCH 3/6] Update all other Laravel release versions

Add in 5.0 for legacy projects
---
 lib/docs/scrapers/laravel.rb | 28 ++++++++++++++++++++--------
 1 file changed, 20 insertions(+), 8 deletions(-)

diff --git a/lib/docs/scrapers/laravel.rb b/lib/docs/scrapers/laravel.rb
index 52997e06d..42d37e409 100644
--- a/lib/docs/scrapers/laravel.rb
+++ b/lib/docs/scrapers/laravel.rb
@@ -56,7 +56,7 @@ class Laravel < UrlScraper
     end
 
     version '5.7' do
-      self.release = '5.7.7'
+      self.release = '5.7.28'
       self.root_path = '/api/5.7/index.html'
       self.initial_paths = %w(/docs/5.7/installation /api/5.7/classes.html)
 
@@ -69,7 +69,7 @@ class Laravel < UrlScraper
     end
 
     version '5.6' do
-      self.release = '5.6.33'
+      self.release = '5.6.39'
       self.root_path = '/api/5.6/index.html'
       self.initial_paths = %w(/docs/5.6/installation /api/5.6/classes.html)
 
@@ -82,7 +82,7 @@ class Laravel < UrlScraper
     end
 
     version '5.5' do
-      self.release = '5.5.28'
+      self.release = '5.5.48'
       self.root_path = '/api/5.5/index.html'
       self.initial_paths = %w(/docs/5.5/installation /api/5.5/classes.html)
 
@@ -95,7 +95,7 @@ class Laravel < UrlScraper
     end
 
     version '5.4' do
-      self.release = '5.4.30'
+      self.release = '5.4.36'
       self.root_path = '/api/5.4/index.html'
       self.initial_paths = %w(/docs/5.4/installation /api/5.4/classes.html)
 
@@ -108,7 +108,7 @@ class Laravel < UrlScraper
     end
 
     version '5.3' do
-      self.release = '5.3.30'
+      self.release = '5.3.31'
       self.root_path = '/api/5.3/index.html'
       self.initial_paths = %w(/docs/5.3/installation /api/5.3/classes.html)
 
@@ -121,7 +121,7 @@ class Laravel < UrlScraper
     end
 
     version '5.2' do
-      self.release = '5.2.31'
+      self.release = '5.2.45'
       self.root_path = '/api/5.2/index.html'
       self.initial_paths = %w(/docs/5.2/installation /api/5.2/classes.html)
 
@@ -134,7 +134,7 @@ class Laravel < UrlScraper
     end
 
     version '5.1' do
-      self.release = '5.1.33'
+      self.release = '5.1.46'
       self.root_path = '/api/5.1/index.html'
       self.initial_paths = %w(/docs/5.1/installation /api/5.1/classes.html)
 
@@ -146,9 +146,21 @@ class Laravel < UrlScraper
       end
     end
 
+    version '5.0' do
+      self.release = '5.0.35'
+      self.root_path = '/api/5.0/index.html'
+      self.initial_paths = %w(/docs/5.0/installation /api/5.0/classes.html)
+
+      options[:only_patterns] = [%r{\A/api/5\.0/}, %r{\A/docs/5\.0/}]
+
+      options[:fix_urls] = ->(url) do
+        url.sub! %r{#{Regexp.escape(Laravel.base_url)}/docs\/(?!\d)}, "#{Laravel.base_url}/docs/5.0/"
+        url
+      end
+    end
 
     version '4.2' do
-      self.release = '4.2.11'
+      self.release = '4.2.22'
       self.root_path = '/api/4.2/index.html'
       self.initial_paths = %w(/docs/4.2/installation /api/4.2/classes.html)
 

From df0fa873cbc8538f4cb7f6f74987ffac6bed77b3 Mon Sep 17 00:00:00 2001
From: James King <james@jamesking56.uk>
Date: Sun, 8 Sep 2019 15:48:52 -0700
Subject: [PATCH 4/6] Update Laravel License URL

---
 assets/javascripts/templates/pages/about_tmpl.coffee | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/assets/javascripts/templates/pages/about_tmpl.coffee b/assets/javascripts/templates/pages/about_tmpl.coffee
index 31e6a93f8..d77d6583b 100644
--- a/assets/javascripts/templates/pages/about_tmpl.coffee
+++ b/assets/javascripts/templates/pages/about_tmpl.coffee
@@ -420,7 +420,7 @@ credits = [
     'Laravel',
     'Taylor Otwell',
     'MIT',
-    'https://raw.githubusercontent.com/laravel/framework/master/LICENSE.txt'
+    'https://raw.githubusercontent.com/laravel/framework/master/LICENSE.md'
   ], [
     'Leaflet',
     '2010-2019 Vladimir Agafonkin<br>&copy; 2010-2011, CloudMade<br>Maps &copy; OpenStreetMap contributors.',

From d705f06c8d92895867c5a863aa64ea78b8e6dba5 Mon Sep 17 00:00:00 2001
From: James King <james@momentum.studio>
Date: Sun, 8 Sep 2019 15:59:02 -0700
Subject: [PATCH 5/6] Update Laravel icons

---
 public/icons/docs/laravel/16.png    | Bin 683 -> 973 bytes
 public/icons/docs/laravel/16@2x.png | Bin 1721 -> 1882 bytes
 2 files changed, 0 insertions(+), 0 deletions(-)

diff --git a/public/icons/docs/laravel/16.png b/public/icons/docs/laravel/16.png
index 1ecf19caea50b31466a9adc8b1c27a830c752989..4347b8cb577e0d85fa5ca90bf2e440333d15269c 100644
GIT binary patch
literal 973
zcmeAS@N?(olHy`uVBq!ia0vp^0wB!63?wyl`GbKJOS+@4BLl<6e(pbstU$g(vPY0F
z14ES>14Ba#1H&(%P{RubhEf9thF1v;3|2E37{m+a><YADU|<vv@CkAKud4u5^Iu2d
zzpmncU3nmv_6TSZ*|rd`7ne#jaWpR2VgLVsy~;Hg7%nj-L4KfMW?+!X=?<+n<*e}*
zFk9X<nVr?TC|M~!A(xA>q(xk;t(Lo(lcTvXRx_qx8o!M#U!Jj%-0XZcM&*NLAr`!o
zSo+$9*nGqqc%rlHvn99_C3SR}Eq$#Vcgar4-g_2kI%ATzyGzWg8w}Hd9QG1VUsv|W
zOl+dMDy-Q8Q-MM+JY5_^Brcm?$PRCE5MX<t$Z|NeBkII0Rg<Mm(JzyhPVJl)Rbsen
z;m`m7+mkQNG5-AU=cjq)3?ioMwHSiTHmno%SQrt-ELq}we0QSM5d-t>4N>2=<pyd@
zEB~}R_1Ik7?M$J?@>zS{UFDasxB1k3Y-5I!z%fA%ZvR=!)3??uEL^7Cp2zlFH#At^
zrJGfI$DXY6b@_L0mmQCE`hM<RV24+fJrieQ!GD96iBEgwC8w)abS?b#=hH7SpC{!T
zS*F!Ae7^a=C}EPyeU2~3y_0!*j^CS-<eDSA^xqom&zE1UH(EC*_{jPh>GBZ_kN3*!
zI`2*bCQ}C064!{5l*E!$tK_0oAjM#0U}&jpV5Dnc7Gh**WnyY&Y^H5sXk}n<=1!9b
ziiX_$l+3hB+#2>aT73a(2(Jo>C<#g|S12gTPs_|nRVb+}NL9!zC`o2usF?Hk6AwpW
zn1;qF|I=qYp9V27D|725a|<gAdruZ&7FKX+FgcvUth_ly;q;9wCytysB6EcObc4qN
aFFl4=;({fgoJ>Ix$KdJe=d#Wzp$P!mM`}<2

delta 670
zcmV;P0%85l2df2;8Gi-<001BJ|6u?C0&+=2K~#9!eUsZu)Ik)-fB#qyJwz{EAT+P7
zcX#uWYblvZmV{-f75b1^OIWEXNh(Me=mHv;wWXv~66UCDnwT2oHkb45%x_8`a(g&1
z%$)Cc=6uc^PhD@`D^KN*$#8Z|mgk6sQJN`a@Tic59HF$B41ed0o4(FHo~$a0@*y}W
zahwQ1)mK18+Mpi|!n_)RdG{J5W`{lf;NB8D|KA{#0zKFZ#N$x+??QE4b%u?#A3Tc3
zg{-fHEJ{mkP!@m;=fX@)K(}3n%sK>FdJM88bIvo-F+uO&@-3-g4v9^U^LfJ=P;3FJ
zuAIdgyq_yPRew_=@M9A?(h3<&*<E}x*G1kD=<W#2WE2e2vJsvvND_LW2lQ=)lk)7Q
zOLp+Mv~+9iqAUyQd<AHA8T4@q^!bzUcvEnImY00OGUqV3RU9dP-Rfd3bk8lAu@TV9
zSJ3x0(EJzBqJVk&kPV8{g$x{kYP|$({e)_7f$r_}pMObftDuc_Uuechp}He%SmWwH
zTMjcbEj$(qJ=6z1(92~k1AudX`5e0ICKQA7;f7ope4*<KL)Cq^g-22fuuu>8L*2Lr
zQW~nQ5i)R)lhSOfZ0*}Hci?8*R`LrPs)Y>yX;Xd@|FTg~Y~G2SaJO)0#Tmk5$`+z^
z->wZ>!GH93G05b9M4ay+^QG#_1>w0N+Ud6yna4vwd<&|o$kyyc1<7tEn(AP<TeP$Y
zXdUz9>Cl8d*fz22%0kfQ27`QN4Vip3ENEJo0}+AN*PvfK0Z;Ozr`ntM@dtYIcbxeZ
z{@Cg}9Rh%$*%?9dm%ldClY$3H$jV?$22-QD=@;Do-#sk@XBBn(KL7v#07*qoM6N<$
Ef(V>M4*&oF

diff --git a/public/icons/docs/laravel/16@2x.png b/public/icons/docs/laravel/16@2x.png
index bbb548f70d54b5e9a8f59d73bdf4cb75f9ac71d2..3200df13d8088e5bd576efcfe1da99aa3598a9ee 100755
GIT binary patch
literal 1882
zcmeAS@N?(olHy`uVBq!ia0vp^3LwnE3?yBabR7dyEa{HEjtmSN`?>!lvVtU&J%W50
z7^>757#dm_7=8hT8eT9klo~KFyh>nTu$sZZAYL$MSD+0815<r~Plzi}!GB$a|GJ9*
zb>;u+tNbuB{I4VbUsvhBp5lLP#eX`g{|%J?%k%%&llreC{a;<=FHlNf>%X4-e;vh-
z+S>nh#Qtk5{L|I=udDLkSo6P{;44#$|9VRQO|<^&$i6c+{;wnVUq|7+w(fr|x&PW~
z|A123O22em{^=_JG|>F7r}7VEwelSXwGY}l-*nXf>uQ4C19TD`0TlodoC{|t;Sh%_
zfH1J?MN@-^i=iDDG6=^Yv+)>$CWWR8jf<uj!TqPF0*V^!p+T%6V8;`$7*i!!1Q?Hq
zKmfWBQyIe9IBop@|7Q3SZeS9;QWE4B45Uc|tUkw2__8u;O*>XpIGs_f;$*+7N?)b8
z%O*=^W{Zus{E0~d6TetneQk8#vU}H7PqwL()QVde^=9V?WX;vrm{OwI)GAulrKr$R
zEy?2G_;)hjgx_t=4f~weZ`)Ha^Bf~nW9`K{sk5n^aR-;1FFTa5CWIqs^=%R1e-FgU
zC63(fwBwFBu&VWS#JauVT;7c8u`6ww+K+ODh6xLn?O)3s6@B=O_Nj>Td;EZ&VodUO
zce%p3o4XarVK4FYb!C6d#3rh%!kR5G6_^#Ldb&7<Se!1s^3z@<QG($^<vmUB@|PD@
z{+__+Q&xU0EB(6Q=^(SEOKx0USoCJssUXj7(?q<MG{3vyvRXvdX}ZW){;&J=HyYiO
zPn%cy{P({1d**+yY)h12tEu_BL-t>XV7|iCla;Ov>!+}G36(AP3dmmO!^<V+<mA}$
z=F#CpTX)DSDV4^E?6}~^>GJ-bF!MT<YwvlxmpbhB-)_%$=f$dj?0m=My)0^2J~%H5
zQdE&#=6n4G>tdUk3?*M~6#jGZIpz89N~UH~L3)<d^t>leB-fne$um|k?mmBRX6J=9
zcZ~nsv|&0h>HTrh2nLQByo}G!xgVBko5?NCr7tFEaGq6f=E2&392(oyUg-UPkjNUI
zqw2*aCa~dyyur+1FUzGm$`gZ^9ElZWcHN-i5gWG5yrLmf=mF#PE1B05H%de}t&{V<
z`AMnlW|3jTjW-WOPfTXoVpPqP@L5YsJO54!XT;R-z|w3Rk9F&I#!A;cf4BGd)u(Af
z?pbpWWNB=>I`v98vrUD>e~;-7k4=*qJcD!lMg327u5VrbDgAumn?C+*5fhU~dm`M=
z@i)ePUG!4bdXCKD154Izzh>$_;W~rvdYQEk*MHQT<M2^BJDPiq`e9wx{QFzWFXUP^
ze)ruvi?_n7MR<yFT2qQm!iDy8Dvqh?2j!GRq|B6#UFMvTxlGABWcA`_ix;n+U3Wt5
zTkv^~j@L(5HocF#@O|g1H{R?Of%ERq<`d%DH?62sa*L9gbJ6(^Irl6$MeiqYvz|D;
zKwL^Xf^+j!IkCrFy!Ts|_`TmK#F!frTOTc-vzX!6t+n>EUanevR+O#o+xD_-&I`xN
zEbDj=eEWZj+cBeK!8ya3#m%ic*4kl<H3HP+WmZXr{F~+%_4MDq`Zl$HEdQ7eh~2mK
zW3K_$FAS<Bt`Q|Ei6yC4$wjF^iowXh&{EgHNY}tD#K_Rf#MH{zOxwWF%D~{vohA<y
z4Y~O#nQ4`{HSBG)`U2DtUKJ8i5|mi3P*9YgmYI{PP*Pcts*qVwlFYzRG3W6o9*)8=
z4UJR&r_Xpk4Pszc=GIH*7FHJao-D#Ftl-jMayW%qd2@)u=^Iy09657D<_P=g29E_^
adJM0`1xr3TnF4be1B0ilpUXO@geCwn5B9|X

delta 1716
zcmV;l221(c4!I4G8Gi-<0047(dh`GQ27pOKK~#9!tygPo6jc-+9s+_WXyOx$JWPxj
zL>nxf_qMg9kajyeGrQY17{sFdumMp6QG@-1CJ;pui7}d>@%2l51(BGj5rdCth*Yei
z_=qGDAW(UBcV_PKJ9jRX+NOxhCMP>PJ@-7m^PO{UHU1p;^nWWU?>s`G^@+%tC!!XE
z$}PHp&;<}tYN<&gPfudcI7WH<11dNxsl}Znom0`cmJ0mRB??T6E|5c(vJ{;}&LHwF
zq7c%SA!@HBYRzn=c6W+Kp|cJVQ8}weP>w6jSa=2@%Tz*0V3vXIe#qApn(rcz_2fHC
z<AU8zZTcJyQGe~Ez!Ifw#m)sFro=Oj!10?@be@QPa|wm6NiF&eYM4DiQ=bEPCX_ub
zLBZ+}p&dtF3ReXZGsMC--=eCji=^$v?l{U-PoaW7mkOD?Q0gav#1`oE;Q4o;l-Foc
z!vqmp+xT!rCCJt=0s<vHOuoH91`yZ}p}dELZ<M$kaDNT~4{~S9WPKx1hyufc!r>%m
zBxO(k-$<0QH3<bkA+UR>Xip`-`bId~gLfQYB*~eT5|M8tK>mA;mNZXHqqUxfG7ME-
zij;uXW@*=-SC8a+lboI~O02_ykZ+R6+ud3c*sG*slRXWk_(23_r9p_uGnfw%AYR6{
z5x{CZ1Aif9R|Non-)V^U7xLYk6bc>q9bst1Q6+;24iY$kt^MSgw^C!{SOoD72hqpL
zosB?B26GcLml_%-KxrESkuX)>6*gzNox+-n`+Rdcp7$XzMxu{7AQ6a>DI6ZBAX6t%
z@GJ)hk20f6*-B85XJgprDY%Ah$G+vGG$r}2=zowXy4{-UUxsTdH8qVVO&fvP@D%z~
z*6jRR5%uR*hTtqe!#O*1``{x;=Z>?6^6p1TV62ZryO{$ZZaoB0qMX&CNHYxweiXx$
z0>&jm>hCezh~>;T`^PXA8@F4J$fN$Dvxx3RnZsFQm=l`%qyZ?X;B+@-=T7DKm<jj6
zP=8s?1tA3vRd%waFm@?DXUlJ7cL2}3@cahOK1fB=Jsq0YQ{zlH9QdI^?F?E}KVKU#
zMDlFNew-DUI574;g%X7_>rhTPgkCy!t)tM{iL775@B1OnUt!JVgPe7Cj-}SR*>T=p
z5(jQE-NJ4m37ucHvs(ucCJ5k9Zk;rUjDLeNoK_A`VMZK406Q>JH!`GU->k;6xq6Vp
zHgj^h&7Ff4-vPbn5#(n;=QlNuPvPC2;M%A-XWt`9D4in+z%KVSl;4vr8HS^9;DIEt
zo{K%Z9YNeoO;zIuIc#mdii)*5Awy*LEJo}XK&KZX)Jo<%fn52_5xo1BP#Sp{Mt@Vn
zpfADLePI9F)atG#KuKNNNNtD@EpC~F3x$IWmnV7WWd!^cY#d25O!*)@qrVl^4iE!I
zb>4cNTz51xehXj60DS}b_0y@@m^i>0f}pO&<EU8gQd`|}w9u=_uv=iuQSeWOF*{^O
zN|f`V=Yv<nLnr~VE3_dq4C^nWR)4z|YxTDDw|fa7`<TlElpv`?)gdv<`3x-%P@<G~
zx-}j=y$j9B><q@2K{g|+&r!=>AhVO^r>q8S3-Gs-=>MpcIu)e~c7<9-d-z7QL9j!#
z6j&}$3eJ$T6Q~mu^_6KU+|l^`64$TdyW_xRG?+B3z<0zX2PNP9nI|I$QGfFETk!k`
zx<yp7ve`BQ;AOR28;&&mUIn<8NE@L_@fZ^?I)4-}y3<w6|97Co-0u6dVI##M&KASy
zAajKIaxzzSjR@>r|7m4&>nTJTVYIvyoIS+LFV0&_wR6G+0}6##Nb4G@P{<4HiO3rg
zIk})1A?_5(sgT7w4B3XPJAd(g2VaI|%O##(j=kYgh(JgjI!1xsAOmo37?*B1TLySG
zcjEp`9Ue*t!SoNI_bAAIJ5Sev?H-QN!2Z1$B*{78jMc>4PVLo~%ENx98mJtBLxGOz
z--;mZ2`WG@bRMRHF^@VMhunloV6Fl>8yL<_fCbE)R~{~iNKG#aoPWFf4dtD+7|ERR
zA++!go~UJZ`mc@1+~H2*(xJ0n6P$E=E#Xq~f=12mOnDC|I&$4c=a^pHI%hWE34BxF
zuArQgp;@!W49e82y8^Zs0+DBcat|_2+21M`-lqukIt7V717mh0*uFOgC#1unP*4}m
z#JARQR)ZXNb&dQ<-YtNg8aP{zjKAbHu1L)1%P3JdoUc2rX3O92N}!iAmu+<b0000<
KMNUMnLSTY*=p+gN


From 8802d344ec98e393d20a7c70095a6202a4a47ead Mon Sep 17 00:00:00 2001
From: James King <james@momentum.studio>
Date: Sun, 8 Sep 2019 17:40:45 -0700
Subject: [PATCH 6/6] Fix container wrappers

---
 lib/docs/filters/laravel/entries.rb | 2 +-
 lib/docs/scrapers/laravel.rb        | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/lib/docs/filters/laravel/entries.rb b/lib/docs/filters/laravel/entries.rb
index 6b7c7dcf7..3b2f0fa0d 100644
--- a/lib/docs/filters/laravel/entries.rb
+++ b/lib/docs/filters/laravel/entries.rb
@@ -13,7 +13,7 @@ def get_name
 
       def get_type
         unless api_page?
-          link = at_css(".sidebar li a[href='#{result[:path].split('/').last}']")
+          link = at_css("section.docs_main li a[href=\"/#{result[:path]}\"]")
           heading = link.ancestors('li').last.at_css('> h2')
           return heading ? "Guides: #{heading.content.strip}" : 'Guides'
         end
diff --git a/lib/docs/scrapers/laravel.rb b/lib/docs/scrapers/laravel.rb
index 42d37e409..23aaf3f05 100644
--- a/lib/docs/scrapers/laravel.rb
+++ b/lib/docs/scrapers/laravel.rb
@@ -10,7 +10,7 @@ class Laravel < UrlScraper
     html_filters.push 'laravel/entries', 'laravel/clean_html'
 
     options[:container] = ->(filter) {
-      filter.subpath.start_with?('/api') ? '#content' : '.docs-wrapper'
+      filter.subpath.start_with?('/api') ? '#content' : 'section.docs_body'
     }
 
     options[:skip_patterns] = [

**Comment by jmerle** [comment]
You'll need to update the clean_html filter in [`lib/docs/filters/laravel/clean_html.rb`](https://github.com/freeCodeCamp/devdocs/blob/master/lib/docs/filters/laravel/clean_html.rb) and possibly the entries filter in [`lib/docs/filters/laravel/entries.rb`](https://github.com/freeCodeCamp/devdocs/blob/master/lib/docs/filters/laravel/entries.rb) to get the scraper to work with the new docs and to categorize everything correctly. The documentation for filters is available [here](https://github.com/freeCodeCamp/devdocs/blob/master/docs/filter-reference.md).

**Comment by jmerle** [comment]
Closing this PR due to inactivity. Feel free to open a new PR in the future.

**Pull request closed without merging**
