### PR TITLE
Update Twig to 3.1.1 and update previous versions

### PR DESCRIPTION
**Pull request by MasterEnoc**
- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by scherepn** [comment]
Good catch on updating the logo, but your logo source was missing an alpha channel.

Here's the same icon, but squared off, and with transparency:
twig-logo

URL is https://twig.symfony.com/images/logo.png

**Comment by scherepn** [comment]
https://github.com/scherepn/devdocs/tree/twig

**Comment by MasterEnoc** [comment]
Thanks @scherepn. Now the logo is the correct one

**Comment by simon04** [comment]
The code blocks contain line numbers and look strange:

Screenshot 2020-12-07 at 11 47 38

**Comment by MasterEnoc** [comment]
Fixed, proceed to review

**Review by simon04 — APPROVED** [review]
Thank you!

**Pull request merged**
