### PR TITLE
Add FastAPI to DevDocs

### LINKED ISSUE #1735: Add Fast API (python library) documentation to devdocs
# Feature request
Add Fast API (python library) documentation to devdocs
## Summary
It is a rather useful library, **superior to flask**, **generates auto-docs** to the APIs made with it and also has **validation methods** to check if arguments are being passed correctly to functions and API routes with a tight **pydantic integration**, none to say it is brutally **faster than flask and django**, this is why it's gaining traction through python community and being adopted as main API library over flask by **machine learning and data science developers**. 

**It just works, as easy to setup as Flask, faster, auto-docs, and has bundled validation method with pydantic** which saves a lot of developer's time not having to code those validations by hand, so I think it would be a great addition to devdocs!

### PR DESCRIPTION
**Pull request by yezz123**
Fixes #1735.

If you’re adding a new scraper, please ensure that you have:

- [x] Tested the scraper on a local copy of DevDocs
- [x] Ensured that the docs are styled similarly to other docs on DevDocs

- [x] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [x] `16.png`: a 16×16 pixel icon for the doc
  - [x] `16@2x.png`: a 32×32 pixel icon for the doc
  - [x] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

### CODE REVIEW

**Comment by yezz123** [comment]
Thank you @simon04 for helping in fixing logo and add missing information 🙏🏻

**Comment by simon04** [comment]
Please update docs/file-scrapers.md and document how to obtain the original documentation files on order to run the scraper. Thanks!

```ERROR: The Fastapi scraper requires the original documentation files to be stored in the "/Users/simon/src/devdocs/docs/fastapi" directory.```

**Review by simon04 — CHANGES_REQUESTED** [review]
.

**Comment by simon04** [comment]
Please provide the missing details and reopen. Thanks!

**Comment by simon04** [comment]
I finally found the docs to download, cool: https://github.com/tiangolo/fastapi/actions/workflows/build-docs.yml?query=branch%3Amaster+actor%3Atiangolo

However, the scraper does not work, at all. No wonder, it's just a 1:1 copy of django! 💢

**Pull request closed without merging**
