### PR TITLE
feat: React.dev docs

### LINKED ISSUE #1997: React documentation is from the old website
# Documentatio bug

The React documentation links to the old React documentation at reactjs.org. The new website is react.dev.

### PR DESCRIPTION
**Pull request by gombosg**
Fixes #1997.
Test with: `bundle exec thor docs:generate react`
TODOs:

- [x] Basic scraper
- [x] Sanitize titles
- [x] Add categories
- [x] Fix code examples
- [x] Remove some more extra styling `div`s
- [x] Syntax highlighting
- [x] Update icon
- [x] Add "Learn" section
- [x] Strip styling classes
- [x] Address category main pages (1 level breadcrumb)
- [x] Fix loading `<figure>` images (base64 is wrong)
- [x] Prefix with category group (e.g. RSC, react-dom etc.)
- [x] Fix callouts (canary, you will learn, pitfalls)
- [x] Fix "show more" expansions
- [ ] Transform recipe links to outgoing links (those example tabs can't be rendered properly, they need JS) - we can live with it in the first release
- [ ] Add more search entries - we won't need them IMO

----

If you’re adding a new scraper, please ensure that you have:

- [x] Tested the scraper on a local copy of DevDocs
- [x] Ensured that the docs are styled similarly to other docs on DevDocs

- [x] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [x] `16.png`: a 16×16 pixel icon for the doc
  - [x] `16@2x.png`: a 32×32 pixel icon for the doc
  - [x] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

If you're updating existing documentation to its latest version, please ensure that you have:

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by gombosg** [comment]
Some fixes are still pending but it's looking good already!
Draft comments are welcome in the meantime, @simon04! 🥰

The only real problem I'm facing is that some `figure`s are not displaying well in the Learn pages. The PNG seems to be transformed to Base64 with a wrong value.
image
image

**Comment by gombosg** [comment]
@simon04 WDYT about the PR's direction? I'm happy to finish it in the coming days.

**Comment by simon04** [comment]
Hi @gombosg, thank you for this great work – I love it! Please go ahead and let me know when/where I should help out.

Regarding the broken images, simply remove the `srcset` attribute – `css('img').remove_attr('srcset')`

**Review by simon04 — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
