### PR TITLE
Add 'report a bug' button

### PR DESCRIPTION
**Pull request by MasterEnoc**
Add 'report bug' button requested in #786.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by simon04 — APPROVED** [review]
Just to mention: GitHub supports passing a custom issue body, e.g. using https://github.com/freeCodeCamp/devdocs/issues/new?labels=bug&body=foo+bar – this way we could automatically prefill the user agent and/or page where the error occurred.

**Comment by ojeytonwilliams** [comment]
Oh, that's neat.  We could include that in this PR if it's a simple tweak (I don't know erbs well enough, honestly).  Otherwise, that could be a follow up.

**Comment by MasterEnoc** [comment]
It could be fine, but the custom issue body will bypass the selection of an issue template; we have two types of bugs templates, doc style and bug report (UI, devdocs features bug, etc), both have different issue body. If it is fine bypass the selection of an issue template I will continue adding the information @simon04 mentioned.

**Comment by j-f1** [comment]
Note that the new issue page (https://github.com/freeCodeCamp/devdocs/issues/new/choose) redirects to a login page if users don’t have a GitHub account. Maybe it would make sense to make a custom support page on devdocs.io that links to each template individually and suggests users create a GH account if they don’t have one yet? I guess it’s true that a DevDocs user is more likely to have a GH account than a random person, though.

**Comment by MasterEnoc** [comment]
Make a new page would end up suggesting the user to make a GH account, right? Unless the page can make anonymous issues (It would be helpful for those who do not want a GH account) I do not find it very useful, I have seen how other bug trackers let make issues via email, I do not know if Github allows that.

**Comment by j-f1** [comment]
Yeah — after adding a GitHub issue link to some Mac apps I wrote I realized that it isn’t really clear why GH would ask you to log in, so I changed the apps to link to a page with my email on it too.

**Pull request merged**
