### PR TITLE
Add PyTorch v1.5.0 documentation

### PR DESCRIPTION
**Pull request by xavieryao**
If you’re adding a new scraper, please ensure that you have:

- [x] Tested the scraper on a local copy of DevDocs
- [x] Ensured that the docs are styled similarly to other docs on DevDocs

- [x] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [x] `16.png`: a 16×16 pixel icon for the doc
  - [x] `16@2x.png`: a 32×32 pixel icon for the doc
  - [x] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

This PR introduces all of PyTorch v1.5.0 Python API docs to DevDocs, excluding notes and language bindings. The categories are identical to the Python API section of [https://pytorch.org/docs/stable/index.html](https://pytorch.org/docs/stable/index.html).

#799 will be solved.

### CODE REVIEW

**Comment by stephenroller** [comment]
+1

**Comment by stephenroller** [comment]
Just tested locally, works great.

**Comment by stephenroller** [comment]
Bump.

**Comment by wogong** [comment]
Really wish this can be merged soon

**Comment by xavieryao** [comment]
The DevDocs repo hasn't been maintained since March, which is sad. I've been running a local DevDocs server only for PyTorch for the recent months.

**Comment by wogong** [comment]
@xavieryao I tried to run a local server using your PR, got a 404 error, any ideas?
`(295/383) PyTorch FAILED (OpenURI::HTTPError: 404 Not Found)`

**Review by simon04 — APPROVED** [review]
Awesome, thank you!

**Comment by stephenroller** [comment]
🥳

**Pull request merged**
