### PR TITLE
Add OpenJDK version 15

### PR DESCRIPTION
**Pull request by MasterEnoc**
- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

This is a WIP PR, Openjdk 16 still has some style issues.

All the tables are made with 'div' tags rather than table (th, tr, td, etc) tags, this has been painfully hard to work with and I have not found a good way to fix this.
image

All the other version work as expected and have good styles.

### CODE REVIEW

**Comment by simon04** [comment]
The resulting OpenJDK 16 documentation is very hard to read (for `Color`):
Screenshot 2021-01-07 at 20 57 12
Screenshot 2021-01-07 at 20 57 28
Screenshot 2021-01-07 at 20 57 46


Should we omit version 16 for now and only add versions 13/14/15?

----

Version 15 could get some syntax highlighting as indicated in this screenshot: 
Screenshot 2021-01-07 at 21 09 11

**Comment by MasterEnoc** [comment]
Version 16 removed and syntax highlight improved for version 15. 

Notice that syntax highlight in the summary tables can lead to undesirable format (at least using prismjs):
image
For this reasons syntax highlight was not added in the summary tables.

**Comment by simon04** [comment]
I've removed versions 13 and 14 since they're end of life and no longer provided on packages.debian.org

**Review by simon04 — APPROVED** [review]
Thank you!

**Pull request merged**
