### PR TITLE
Fix Erlang lib/ entries and func Types sec

### LINKED ISSUE #795: Erlang documentation is not correctly indexed
As of commit d48396d, the Erlang documentation is not correctly indexed and/or not correctly searched:

There are two problems, since they may be related, I put both of them here:

1. Search with `lists:sum` should show documentation about the function `lists:sum`, but empty results are returned instead. (not all are badly indexed, for example, search `gen_server:call` works as expected.

image

2. Some functions of the `lists` module is missing in the export list. See the below two screenshots.

Wrong behaviour (only one export is shown)
image

Expected behaviour (many exports are shown)
image

### PR DESCRIPTION
**Pull request by axelf4**
This pull request

* Makes lib/ entries get indexed correctly;
* Stops the types associated with functions from being filtered away, and orders their "Types" heading under the function heading; and
* Cleans out onmouseover/onmouseout attributes.

Closes #795

If you're updating existing documentation to its latest version, please ensure that you have:

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches its data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by simon04** [comment]
Thanks a lot for this PR. The results look very promising. What's left to be done?

Just to make sure, here's how to provide the source docs: https://github.com/freeCodeCamp/devdocs/blob/main/docs/file-scrapers.md#erlang

**Comment by axelf4** [comment]
> What's left to be done?

I had only been concerned with OTP 25 initially. I have now to the best of my ability gone through older versions to ensure their indexing is also correct, and that there are no regressions.

**Review by simon04 — APPROVED** [review]
Thank you!

**Comment by simon04** [comment]
Great! I've updated Erlang v25 and v24.

**Comment by Stratus3D** [comment]
This is awesome! 🔥 Thank you @axelf4 !

**Pull request merged**
