### PR TITLE
Update PostgreSQL to version 11 (release 11.5)

### PR DESCRIPTION
**Pull request by filalex77**
- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by filalex77** [comment]
I'm having trouble building and testing this PR locally. Here's the error I have when running `bundle exec thor docs:generate postgresql --version 11`: https://gist.github.com/filalex77/f8ca779ee47f488127ca71ec59c63e5d.

Would be great if someody could help me on this :)

**Comment by jmerle** [comment]
Be careful when copying and pasting existing code. In this case, the `base_url` for version 11 should be `https://www.postgresql.org/docs/11/` instead of `https://www.postgresql.org/docs/11/static/` (try going to the latter in the browser, it'll redirect to the former).

**Comment by filalex77** [comment]
@jmerle Oh, I noticed that, but thought that was the expected behavior (`https://www.postgresql.org/docs/10/static/` did the same for me)

I'll update that.

**Comment by jmerle** [comment]
Thanks, looks good! The PostgreSQL 11.5 docs are now available at [https://devdocs.io/postgresql~11/](https://devdocs.io/postgresql~11/).

**Pull request merged**
