### PR TITLE
Fix Openjdk additional entries and style

### LINKED ISSUE #1326: OpenJDK 11 scrapper does not pick fragment links
The OpenJDK documentation structure changed slightly between the 8 and 11 releases.  One particular change is that _anchor names_ are no longer used.  Instead, the Javadoc HTML uses _anchor **ids**_.  In other words, the _linkable_ parts of a single page went from:

``` html
<a name="mapToLong-java.util.function.ToLongFunction-">
```

In version 8, to:

``` html
<a id="mapToLong(java.util.function.ToLongFunction)">
```

In version 11.  Note also the use of parenthesis in method identifiers.  Because the current scrapper is not able to identify anchor points in the OpenJDK 11 documentation, the method names are **not** being indexed and inner page links don't work either.

I believe the fix for this would consist of updating [this block][s] with two alternative versions:

- One for version 8, just as it is
- Another one for version 11, replacing `css('a[name]')` with `css('a[id]')`

I currently don't have the expertise to prepare and test a patch, so I'm reporting this just in case someone else can fix it in a shorter time.  However, if nobody else can I'll try to do it myself in the near future.

[s]: /freeCodeCamp/devdocs/blob/master/lib/docs/filters/openjdk/clean_html.rb#L9-L17

### PR DESCRIPTION
**Pull request by MasterEnoc**
Fix #1326 and improve style. 

Now additional entries should be generated in version 11 and 15, improvement in tables styles and add more documentation.

### CODE REVIEW

**Review by simon04 — APPROVED** [review]
Awesome, thank you!

**Comment by etanol** [comment]
When will this go _live_?

**Comment by ojeytonwilliams** [comment]
Hi @etanol, it should have gone live when it was merged.  Are the changes not appearing for you?

**Comment by etanol** [comment]
The #1326 issue seems to have been fixed for OpenJDK 15 but **not** for OpenJDK 11.  Which is strange, because the _anchor style_ was changed in OpenJDK 11 and should be the same as in OpenJDK 15.

**Comment by ojeytonwilliams** [comment]
Ah, I think I understand the problem.  It looks like, though the scrapers have been updated for OpenJDK 11, the updated docs haven't been uploaded for that version.

@simon04 if I scrape those docs and upload them, they'll get picked up the next time we merge a PR, right?

**Comment by simon04** [comment]
@etanol, sorry, my bad. I skimmed over the PR too quickly and did not notice that it also fixes OpenJDK 11. I've updated the release to [11.0.10](https://packages.debian.org/sid/all/openjdk-11-doc) and pushed an update via c9d6e8e0b46dc6fbc1e25e431aa5809832c264e3.

@ojeytonwilliams, yeah, that should work as well...

**Comment by ojeytonwilliams** [comment]
Thanks for fixing that @simon04 and thanks @etanol for letting us know it had slipped through.

**Comment by etanol** [comment]
Fix verified!  All OpenJDK versions how have a more complete index.  Thank you very much for all the help :-)

**Pull request merged**
