### PR TITLE
docs/maintainers: update list of maintainers

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by simon04** [comment]
@ojeytonwilliams, ping!

Maybe we should distinguish between active and former maintainers?

**Comment by ojeytonwilliams** [comment]
Hey Simon.  Yeah, I like that idea - it's a good way to acknowledge people's efforts, but makes it clear who should and should not be contacted about DevDocs.

**Comment by simon04** [comment]
Maybe change the section heading to "We appreciate major contributions from the following great people"?

**Comment by ojeytonwilliams** [comment]
Tiny nitpick, but I'd say "We appreciate the major contributions made by these great people".  The original sentence sounded a bit like we only wanted PRs from the former maintainers. I tried to make it clear that we appreciate the contributions they have already made.

**Comment by simon04** [comment]
When talking about contributors, we should include additional people from https://github.com/freeCodeCamp/devdocs/graphs/contributors.

Um, complicated. We've the current team (to be contacted via `@freeCodeCamp/devdocs`), former maintainers, and diligent contributors.

**Comment by ojeytonwilliams** [comment]
I think it's fine to just list maintainers and former maintainers.  After all, anyone can go look at the insights tab if they want info about who contributed in general.

**Comment by simon04** [comment]
I've updated the section. @ojeytonwilliams, please review.

**Review by ojeytonwilliams — APPROVED** [review]
Perfect, thanks Simon.

**Pull request merged**
