### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mohamed3nan**
Add a new project to Related Projects.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
Nice tool @mohamed3nan. While there are already some VSCode extensions, I think it's fine to add one more.

LGTM :+1:

**Comment by mohamed3nan** [comment]
Thank you, I test both of them, one is not working and the second is just opening a URL in the browser and I think this is not helpful, so I decided to create my extension that opens a tab inside vscode to help view and explore any docs inside vscode.

**Comment by MasterEnoc** [comment]
Thank you. 

@mohamed3nan what is the extension that is not working anymore? 
@ojeytonwilliams Should we delete the unmaintained related projects (the ones that do not work anymore) in the README.md? or we can add a section with unmaintaned related projects.

**Comment by mohamed3nan** [comment]
> Thank you.
> 
> @mohamed3nan what is the extension that is not working anymore?
> @ojeytonwilliams Should we delete the unmaintained related projects (the ones that do not work anymore) in the README.md? or we can add a section with unmaintaned related projects.

this one:  [vscode-devdocs for VS Code ](https://marketplace.visualstudio.com/items?itemName=akfish.vscode-devdocs)
you can see that "Last Commit: 4 years ago" also the developer mentions that ["It is not recommended to use this extension any more."](https://github.com/akfish/vscode-devdocs/blob/master/README.md#vscode-devdocs-readme)

**Review by KenG-pro — APPROVED** [review]

**Pull request merged**
