### PR TITLE
Add documentation for OCaml

### PR DESCRIPTION
**Pull request by seirl**
If you’re adding a new scraper, please ensure that you have:

- [x] Tested the scraper on a local copy of DevDocs
- [x] Ensured that the docs are styled similarly to other docs on DevDocs
- [x] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [x] `16.png`: a 16×16 pixel icon for the doc
  - [x] `16@2x.png`: a 32×32 pixel icon for the doc
  - [x] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

Additional information: This required an update to Prism with OCaml highlighting.

---

image

### CODE REVIEW

**Comment by ELLIOTTCABLE** [comment]
Anything in particular blocking this? I'd love to get it merged!

**Comment by s0kil** [comment]
LGTM

**Comment by seirl** [comment]
Is there anything I can do to help get this merged?

**Comment by gengjiawen** [comment]
@j-f1 Can you review this ? thanks.

**Review by simon04 — CHANGES_REQUESTED** [review]
Thank you for this PR. Looking forward to seeing OCaml being present on devdocs. I did my bachelor and master projects in OCaml.

The HTML needs more cleanup (highlighted in red means to be cleaned/removed):
* 
* 
* 
* 
* 
* please provide links to the original documentation (to be used with alt+o)

**Review by simon04 — APPROVED** [review]
Awesome, thanks for contributing the OCaml scaper. I've polished it a bit and update to OCaml version 4.11 :rocket:

**Comment by seirl** [comment]
Oh, thanks a lot for doing the polishing yourself, I wasn't sure when I would be able to get around doing it!

**Pull request merged**
