### PR TITLE
Update Rethinkdb to 2.4.1

### PR DESCRIPTION
**Pull request by MasterEnoc**
- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Review by simon04 — COMMENTED** [review]
Scraping Ruby fails with 

```
$ bundle exec thor docs:generate --force --package rethinkdb --version ruby --debug
...
Process: rethinkdb.com/api/ruby/status/                                                                                                        [43ms]
Process: rethinkdb.com/api/ruby/reconfigure/                                                                                                   [53ms]
[####################################################################################################] [237/237] [100.00%] [00:15] [00:00] [ 15.34/s]bundler: failed to load command: thor (/home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/bin/thor)
NoMethodError: undefined method `>=' for nil:NilClass
  /home/simon/src/devdocs/lib/docs/core/entry_index.rb:59:in `sort_fn'
  /home/simon/src/devdocs/lib/docs/core/entry_index.rb:49:in `block in entries_as_json'
  /home/simon/src/devdocs/lib/docs/core/entry_index.rb:49:in `sort!'
  /home/simon/src/devdocs/lib/docs/core/entry_index.rb:49:in `entries_as_json'
  /home/simon/src/devdocs/lib/docs/core/entry_index.rb:32:in `as_json'
  /home/simon/src/devdocs/lib/docs/core/entry_index.rb:36:in `to_json'
  /home/simon/src/devdocs/lib/docs/core/doc.rb:142:in `store_index'
  /home/simon/src/devdocs/lib/docs/core/doc.rb:116:in `block in store_pages'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block (2 levels) in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:182:in `track_touched'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `block in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:170:in `lock'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:87:in `replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `block in replace'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:144:in `open_yield_close'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:30:in `open'
  /home/simon/src/devdocs/lib/docs/storage/abstract_store.rb:85:in `replace'
  /home/simon/src/devdocs/lib/docs/core/doc.rb:107:in `store_pages'
  /home/simon/src/devdocs/lib/docs.rb:100:in `generate'
  /home/simon/src/devdocs/lib/tasks/docs.thor:306:in `generate_doc'
  /home/simon/src/devdocs/lib/tasks/docs.thor:106:in `generate'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/runner.rb:43:in `method_missing'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:29:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:135:in `run'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/bin/thor:6:in `<top (required)>'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/bin/thor:23:in `load'
  /home/simon/src/devdocs/vendor/bundle/ruby/2.7.0/bin/thor:23:in `<top (required)>'
```

**Comment by MasterEnoc** [comment]
I changed how versions are implemented, I think now is more readable; and, the scraper is fixed in all versions. 
One page was returning an empty string as its entry name, this made 'sort_fn' method of the 'EntryIndex' class stop working properly.

**Comment by simon04** [comment]
The code display and syntax highlighting are broken for some examples:

ksnip_20201216-190932

**Comment by MasterEnoc** [comment]
Should be fix now, proceed to review.

**Review by simon04 — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
