### PR TITLE
Add a Terraform scraper

### PR DESCRIPTION
**Pull request by dig412**
I've added a scraper for the Terraform cloud management tool (https://www.terraform.io/docs).

My main driver for this is the ridiculous unwieldy length of the AWS provider page (https://www.terraform.io/docs/providers/aws/index.html), which is very hard to navigate despite being one of the main reasons to use Terraform.

I've added special case handling for AWS, Azure and Google Cloud, as they all have more than a hundred pages in their categories. This makes it difficult to browse, so I've made the scraper add an extra layer of category for them. I didn't want to do this for all providers as many only have a couple of pages so the extra types are unnecessary.

I based this off the existing Vagrant scraper, as the projects are from the same company so share styles and layout.

This is my first time writing any Ruby, so any criticism / feedback is welcome.

Some stats from an import:
```
Entries: (169 KB, +0 KB)
  Updated: 1415
  Created: 0
  Deleted: 0
Types:
  Updated: 171
  Created: 0
  Deleted: 0
Files: (6.9 MB, +0.0 MB)
  Updated: 1553
  Created: 0
  Deleted: 0
Done
```

### CODE REVIEW

**Comment by kedare** [comment]
I would LOVE to see this in devdocs :)
This is the doc I was waiting for a long time.

**Comment by Thibaut** [comment]
Hey there - sorry for the lack of response. I'm currently not able to devote much time to DevDocs beyond doing some documentation updates. We're working with freeCodeCamp to try to find new active maintainers — hopefully soon :)

**Comment by Thibaut** [comment]
Merged in 716fc26af1ffa5dadbe99a01a7037ae7f2f68b9d. Tweaked in b4cd5f1802a9ea178b824f63d3f622de9d6641b4. Thanks for the great PR!

https://devdocs.io/terraform/

**Comment by dig412** [comment]
Amazing, thanks for all your hard work on devdocs!

**Comment by gs-rickchristy** [comment]
Thank you. This is missing the Language section of the terraform documentation.

https://www.terraform.io/language

Is it possible to add this too?

Thank you ! Very grateful regardless.

**Pull request closed without merging**
