### PR TITLE
Add Salt Stack documentation

### PR DESCRIPTION
**Pull request by dotboris**
This PR adds a scraper for SaltStack's documentation which can be found at https://docs.saltstack.com/en/latest/ref/index.html

It focuses on only covering the references of the SaltStack documentation while skipping all the tutorials and other long form documentation.

I believe that this documentation is generated both from the [python code in the repository](https://github.com/saltstack/salt/tree/develop/salt) and the [RST documentation](https://github.com/saltstack/salt/tree/develop/doc). Both of those are licensed under [Apache 2.0](https://github.com/saltstack/salt/blob/develop/LICENSE)

There are two Trello cards for this
- https://trello.com/c/w7DAm30w/452-saltstack
- https://trello.com/c/YqwRdNNz/283-salt-aka-saltstack

### CODE REVIEW

**Comment by neeravkumar** [comment]
Is there anything blocking this PR?
This would be a great addition to devdocs.

**Comment by j-f1** [comment]
Just @Thibaut having time to merge.

**Comment by yonguelink** [comment]
@Thibaut @j-f1 What's up with this? It'd really be a great addition.

**Comment by jmerle** [comment]
@yonguelink see https://github.com/freeCodeCamp/devdocs/pull/882#issuecomment-459763347.

**Comment by jmerle** [comment]
Thanks! Deployed to [https://devdocs.io/saltstack/](https://devdocs.io/saltstack/).

**Pull request merged**
