### PR TITLE
Dart docs latest version

### PR DESCRIPTION
**Pull request by jagomf**
**UPDATED**

Updated latest 2.x stable version.

---

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches its data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by MasterEnoc** [comment]
Hi @jagomf, Dart is a FileScraper documentation, It should not make any http request for documentation. I tried to scrape the documentation without the `index.html` path and I did not get any 404 request.

**Comment by jagomf** [comment]
>  I did not get any 404 request.

Did you make sure you could scrape any 2.x version other than latest stable, or any 1.x version as well?

**Comment by simon04** [comment]
I could update Dart to 2.13.0 https://github.com/freeCodeCamp/devdocs/commit/314010b205fa5aaaa91cfb9803f6a62306605622 without this patch without problems.

**Comment by jagomf** [comment]
Ok, I guess I had missed something.

Left only the latest docs version.

**Pull request closed without merging**
