### PR TITLE
Update Django documentation (3.0.2)

### PR DESCRIPTION
**Pull request by adamchainz**
If you're updating an existing documentation to it's latest version, please ensure that you have:

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by adamchainz** [comment]
Thanks for all the checklists which made it easy to make a PR!

**Comment by adamchainz** [comment]
I guess I have to transfer the packages somehow?

**Comment by j-f1** [comment]
Thank you for contributing! I made a couple of fixes in d1167597 and cb790e95.

**Comment by adamchainz** [comment]
🚀

**Pull request merged**
