### PR TITLE
Add MariaDB documentation

### PR DESCRIPTION
**Pull request by jmerle**
Added a scraper for the MariaDB documentation ([Trello card](https://trello.com/c/AoALaJoT)).

The documentation is licensed under the [Creative Commons Attribution 3.0 Unported License and the GNU Free Documentation License](https://mariadb.com/kb/en/library/documentation/+license/).

The official logo can't be used because the [original proportions must be retained](https://mariadb.com/kb/en/library/mariadb-trademark-policy/#logo-usage), and those original proportions are not a square.

Types:

### CODE REVIEW

**Comment by beaucarnes** [comment]
@jmerle Are you able to fix the image links? On some or all images, the original image links get modified.
 For instance, in this page: http://localhost:9292/mariadb/columns-storage-engines-and-plugins/storage-engines/myrocks/about-myrocks-for-mariadb/index

The first image link is `http://kb-mirror.mariadb.com/kb/en/library/documentation/columns-storage-engines-and-plugins/storage-engines/myrocks/about-myrocks-for-mariadb/+image/mariaDBstorageEngineOpt`.

The link should be `https://mariadb.com/kb/en/about-myrocks-for-mariadb/+image/mariaDBstorageEngineOpt`

**Comment by jmerle** [comment]
Will do that (and fix the merge conflict) on saturday.

**Comment by PowerKiKi** [comment]
Is there anything left to do in order to merge this PR ?

**Comment by jmerle** [comment]
Nope, but it might take a while before it's merged because there are 7 open PR's older than this one and the move of the project to freeCodeCamp is not complete yet (it's getting close though).

**Comment by j-f1** [comment]
Basically, @Thibaut had almost no time to maintain this project and merge PRs like this one, so he handed it off to freeCodeCamp, which will be able to assign at least one engineer to work on this more often.

**Comment by ab-pivot** [comment]
Hey @Thibaut, @ahmadabdolsaheb do you have any ETA on this PR merge?

**Comment by jmerle** [comment]
The latest commit makes the scraper scrape from https://mariadb.com/kb/en/ instead of the old https://kb-mirror.mariadb.com/ since the latter seems to have been taken down. Unfortunately the official website doesn't make it possible to distinguish between MariaDB Server documentation and the other pages in the knowledge base based on url, which is why I used a little workaround to be able to make this decision in a scraper where it is possible to make the decision based on content on the page.

**Comment by j-f1** [comment]
For the logo, we could use a the seal logo embedded in a square image, like this one:

mariadb

**Comment by jmerle** [comment]
I've added the icon you suggested, it looks good.

**Comment by jmerle** [comment]
@j-f1 any chance you can check out this PR and #970? Would be nice to finally get this merged after 15 months :)

**Comment by jmerle** [comment]
I believe enough time has passed for this PR and #970 to be reviewed, so I'm merging them despite not having a review approval.

**Comment by sbrl** [comment]
Awesome, thanks so much! :D :D :D

(btw, is it possible to write a scraper in Node at all? Contributing a scraper sounds cool, but I don't know ruby.

**Comment by jmerle** [comment]
No, scrapers can only be written in Ruby.

**Comment by sbrl** [comment]
That's a shame. Maybe one day I'll learn Ruby then.

**Pull request merged**
