### PR TITLE
Add Perl alias

### PR DESCRIPTION
**Pull request by zoidbergwill**
Closes https://github.com/freeCodeCamp/devdocs/issues/855

### CODE REVIEW

**Comment by j-f1** [comment]
This alias should already work if you have the Perl docs enabled. Is it not working for you?

**Comment by zoidbergwill** [comment]
Ahhh, sorry about that, I think I was misunderstanding how aliases work, and they just happened to work with my test cases. If it's just replacing a word with another word in searches, then I guess this replacement wouldn't make much difference because of fuzzy matching. Unfortunately most Perl documentation pages don't include `Perl` in the documentation page title, or it'd work how I wanted.

I thought it would only search the docs related to that language, my bad. I misinterpreted the docs.

**Comment by j-f1** [comment]
If you type `pl` and hit <kbd>tab</kbd>, a `Perl` tag should show up in the search box, and searches will be limited to Perl.

**Comment by Thibaut** [comment]
Sounds like this unnecessary. Feel free to reopen if not.

**Pull request closed without merging**
