### PR TITLE
Update react-native docs to 0.62

### LINKED ISSUE #1214: update React Native to 0.62

### PR DESCRIPTION
**Pull request by alexbrazier**
**SECTION B - Updating an existing documentation to it's latest version**

Update react-native docs to latest version (0.62)

- Closes #1214

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by rickmacgillis** [comment]
Any updates on this?

**Comment by Fred-Reis** [comment]
where's the doc?

**Comment by alexbrazier** [comment]
> where's the doc?

They get generated by the config

**Comment by chakrihacker** [comment]
Any updates on this?

**Review by simon04 — CHANGES_REQUESTED** [review]
The scraper no longer works due to the [React Native Documentation Update](https://reactnative.dev/blog/2020/07/23/docs-update). All CSS selectors need to be checked/updated.

**Pull request closed without merging**
