### PR TITLE
Add documentation for gnuplot

### PR DESCRIPTION
**Pull request by Cimbali**
Hi there ! I’m making a pull request to add gnuplot documentation, because it is a widespread tool for plotting. and because they do not update their online HTML documentation since version 4.2 (the manual is only up-to-date in pdf at http://gnuplot.info/documentation.html). As far as I know, 8ve followed all the guidelines from the contributing guide, however I’m not very experimented with ruby (yet?), so please be specific for any style/coding conventions I inadvertently missed.

Here’s the checklist, more comments below:

- [x] Tested the scraper on a local copy of DevDocs
- [x] Ensured that the docs are styled similarly to other docs on DevDocs

- [x] Added these files to the <code>public/icons/*your_scraper_name*/</code> directory:
  - [x] `16.png`: a 16×16 pixel icon for the doc
  - [x] `16@2x.png`: a 32×32 pixel icon for the doc
  - [x] `SOURCE`: A text file containing the URL to the page the image can be found on or the URL of the original image itself

---

Documentation is part of the [gnuplot source code](https://sourceforge.net/p/gnuplot/gnuplot-main/ci/master/tree/docs/). This can be redistributed, according to the [copyright notice](https://sourceforge.net/p/gnuplot/gnuplot-main/ci/master/tree/Copyright) (emphasis mine):

> \* Copyright 1986 - 1993, 1998, 2004   Thomas Williams, Colin Kelley
> \*
> \* Permission to use, copy, and distribute this software **and its**
> \* **documentation** for any purpose with or without fee is hereby granted,
> \* provided that the above copyright notice appear in all copies and
> \* that both that copyright notice and this permission notice appear
> \* in supporting documentation.

The term “gnuplot license” is not very widespread but brings satisfying results on search engines (including on wikipedia), so I took the liberty to add a link to the copyright file, taken from the “Gnuplot's copyright” link on the gnuplot home page, http://gnuplot.info.

Here is how to build the gnuplot docs to parse them (requires `latex2html` and basic build tools such as `autotools` and a C compiler):

    mkdir gnuplot-src gnuplot-conf $DEVDOCS_ROOT/docs/gnuplot
    git clone -b 5.2.7 --depth 1 https://git.code.sf.net/p/gnuplot/gnuplot-main ./gnuplot-src
    cd gnuplot-src/
    ./prepare
    cd ../gnuplot-conf
    ../gnuplot-src/configure
    cd docs/
    make nofigures.tex
    latex2html -html 5.0,math -split 4 -link 8 -long_titles 5 -dir $DEVDOCS_ROOT/docs/gnuplot -ascii_mode -no_auto_link nofigures.tex

### CODE REVIEW

**Comment by Cimbali** [comment]
There was an error in the png format that is now fixed.

**Comment by Cimbali** [comment]
I’m attaching the [gnuplot.tar.gz](https://github.com/freeCodeCamp/devdocs/files/3831580/gnuplot.tar.gz) package (552KB) generated by `thor docs:package gnuplot` for those who can not/do not want to generate from source themselves.

**Comment by j-f1** [comment]
I’m getting this error when running the scripts you suggest. Is this something that can be ignored?

```
Translating images to DVI using latex ...
Fatal (syswait): exec " ./images.tex" failed: Permission denied
 at /usr/local/bin/latex2html line 3808.

Cannot read logfile './images.log': No such file or directory
```

**Comment by j-f1** [comment]
It also seems like my `index.html` is malformed:

```html
<BR>

<H2><A ID="SECTION07000000000000000000">
Index</A>
</H2><tex2html_idx_mark>
```

**Comment by Cimbali** [comment]
Hi @j-f1, thanks for taking the time to look into this PR.

- I’ve redone all the steps from the gnuplot source code without problems. Can you specify which step does not work for you? What’s your latex2html version? The other steps should really be straightforward but to be honest there is no images.tex anywhere in the source so I don’t know where this error message comes from.
- In the mean time, I have provided the compiled documentation [as tar tarball](https://github.com/freeCodeCamp/devdocs/files/3831580/gnuplot.tar.gz) if you want to look into it while these compilation problems are solved
- An alternative to compiling the gnuplot documentation is to use distributed packages but those are much harder to parser for devdocs as page names are meaningless (i.e. `nodeN.html`) and the granularity of topics per page is not controlled.

**Comment by j-f1** [comment]
I have latex2html version 2019.2 (Released June 5, 2019). All the commands work fine until `latex2html`, which outputs this and exits with status code 2:

<details>

```
This is LaTeX2HTML Version 2019.2 (Released June 5, 2019)
by Nikos Drakos, Computer Based Learning Unit, University of Leeds.

Revised and extended by:
 Marcus Hennecke, Ross Moore, Herb Swan and others
...producing markup for HTML version 5.0  with math extensions

Extension: loading /usr/local/Cellar/latex2html/2019.2/versions/unicode.pl
*** Constructing conversion utf-8 -> Unicode ***

HTML version: loading /usr/local/Cellar/latex2html/2019.2/versions/html5_0.pl

Extension: loading /usr/local/Cellar/latex2html/2019.2/versions/math.pl
 *** processing declarations ***

OPENING /Users/jed/Documents/github-clones/devdocs/tmp/gnuplot-conf/docs/nofigures.tex 

Cannot create directory ../../../docs/gnuplot/: File exists, reusing it.

Note: Working directory is /Users/jed/Documents/github-clones/devdocs/docs/gnuplot
Note: Images will be generated in /private/tmp/l2h62275

texexpand V2019.2 (Released June 5, 2019)

texexpand: include titlepag.tex failed. Reinserting  command



Loading /usr/local/Cellar/latex2html/2019.2/styles/texdefs.perl...
Reading ...

[... snipped lots of output ...]

575/578:sectionstar:."External libraries" for External_libraries.html
;.....;.......
..
576/578:part:.."Index" for Index.html
;;
..
577/578:textohtmlindex:.."Index" for Index.html
;;
..
578/578:partstar:.."About this document ..." for About_this_document.html
;;.

Writing image file ...


Translating images to DVI using latex ...
Fatal (syswait): exec " ./images.tex" failed: Permission denied
 at /usr/local/bin/latex2html line 3808.

Cannot read logfile './images.log': No such file or directory
```

</details>

**Comment by Cimbali** [comment]
I believe the line `texexpand: include titlepag.tex failed.` could be the cause for the index.html being malformed.

There are basically no images with the `-ascii_mode` option, intentionally so because there are few of them, and generating them is basically broken (and would require some amount of patching). I'll look into what images.tex is, but I suspect it might be a generated index of all included images. In that case we can safely ignore that error, provided the rest of the pages are built correctly.

**Comment by j-f1** [comment]
Currently the scraper assumes that the index page has content and crashes here:

https://github.com/freeCodeCamp/devdocs/blob/3e04069b69f411e001da63016b33f18bb114b3ba/lib/docs/filters/gnuplot/clean_html.rb#L15

because there is no `.HUGE` element.

**Comment by Cimbali** [comment]
I seem to have found the problem for the titlepage. The configure process is not working correctly, or is not intended to generate documentation in a different directory, so `titlepag.tex`, which is not generated by the Makefile, remains in the source directory, while `nofigures.tex` is generated in the configure directory. A solution is to configure in the source directory:

```
mkdir gnuplot-src $DEVDOCS_ROOT/docs/gnuplot
git clone -b 5.2.7 --depth 1 https://git.code.sf.net/p/gnuplot/gnuplot-main ./gnuplot-src
cd gnuplot-src/
./prepare
./configure
cd docs/
make nofigures.tex
latex2html -html 5.0,math -split 4 -link 8 -long_titles 5 -dir $DEVDOCS_ROOT/docs/gnuplot -ascii_mode -no_auto_link nofigures.tex
```



Interestingly latex2html only tried to generate images for me when the title page was missing:

```
[…]
552/552:partstar:.."About this document ..." for About_this_document.html
;;.

Writing image file ...

Translating images to PDF using pdflatex ...
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/TeX Live for SUSE Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./images.tex
LaTeX2e <2018-12-01>

 *** processing  images ***

Transforming PDF images using gs/png16m ...

Doing section links ......
[…]
```

Whereas on runs with `titlepag.tex` found, this step seems skipped:

```
[…]
578/578:partstar:.."About this document ..." for About_this_document.html
;;.

Doing section links ......
[…]
```

So hopefully configuring in the source directory fixes everything. Otherwise it might be worth looking into what the installed latex tools are. Typically your script seems to generate DVI images with latex, whereas mine generates PDF images with pdflatex.

**Comment by Cimbali** [comment]
OK so images are attempted to be generated on the first run only. Their generation is not working for me in gnuplot `5.2.7` (version at the time of the PR) but seems fixed with the latest release (`5.2.8`).

**Comment by j-f1** [comment]
I think I see the problem now:

```
Fatal (syswait): exec " ./images.tex" failed: Permission denied
 at /usr/local/bin/latex2html line 3808.
```

This comes from this section of the html2latex code:

```perl
sub make_latex_images{
    &close_dbm_database if $DJGPP;
    local($dd) = $dd; $dd = '/' if ($dd eq "\\");
    local($latex_call);
    if ($USE_PDFTEX) {
      print "\nTranslating images to PDF using pdflatex ...\n";
      $latex_call = "$PDFLATEX .$dd${PREFIX}images.tex";
    } elsif ($USE_LUATEX) {
      print "\nTranslating images to PDF using lualatex ...\n";
      $latex_call = "$LUALATEX .$dd${PREFIX}images.tex";
    } elsif ($USE_LUADVI) {
      print "\nTranslating images to DVI using dvilualatex ...\n";
      $latex_call = "$DVILUALATEX .$dd${PREFIX}images.tex";
    } else {
      print "\nTranslating images to DVI using latex ...\n";
      $latex_call = "$LATEX .$dd${PREFIX}images.tex";
    }
    print "$latex_call\n" if (($DEBUG)||($VERBOSITY > 1));
    L2hos->syswait($latex_call);
    &open_dbm_database if $DJGPP;
}
```

Could the issue be that I don’t have LaTeX installed?

**Comment by Cimbali** [comment]
I think indeed if you reach the last case in the if and `$LATEX` evaluates to empty, then you’ll try to exec images.tex. I can’t seem to find a way for latex2html to not generate images for the few math formulas it doesn’t manage to inline.

**Comment by j-f1** [comment]
Here’s why it was failing: https://github.com/Homebrew/homebrew-core/issues/25024. I’ll try fixing those values.

**Comment by j-f1** [comment]
I think I got it working. https://devdocs.io/gnuplot/

**Pull request merged**
