### PR TITLE
Fix broken HTTP scraper by only scraping MDN

### PR DESCRIPTION
**Pull request by Elchi3**
### Problem

I wondered why the HTTP docs aren't updated anymore and noticed that the scraper currently fails on `main` for the rfc scraping.

```
$ thor docs:generate http  

ERROR:                                                                                                                         
  https://datatracker.ietf.org/doc/html/rfc4918
  Docs::ContainerFilter::ContainerNotFound: element '.content' could not be found in the document, url=https://datatracker.ietf.org/doc/html/rfc4918
```

### Proposed fix

I think it would be fine to remove the RFC scraping and only use MDN pages, but I don't know why the RFC specs were scraped here in the first place, so let me know if it is a bad idea to remove them. I thought it's a good idea because:

- If you look at ["Status"](https://devdocs.io/http-status/), you mostly see duplicated status entries. 
- We recently completed the MDN HTTP docs by also documenting previously missing WebDAV status codes etc.
- If there are other things the MDN HTTP docs should provide, let me know! :) 

This PR:
- moves the HTTP scraper into the mdn folder (so it lives with the other mdn scrapers)
- removes all RFC scraping
- Adds two new HTTP nav items "Permissions-Policy" and "CORS errors" for better navigation.

### CODE REVIEW

**Comment by Elchi3** [comment]
Rebased after https://github.com/freeCodeCamp/devdocs/pull/1966 was merged. 
Re-added `self.links` and I believe `options[:attribution]` shouldn't be needed because it should be inherited from `mdn.rb`?

**Comment by Elchi3** [comment]
Any chance to get this reviewed? Should I submit smaller PRs that only do parts of this?

**Review by simon04 — CHANGES_REQUESTED** [review]
Removing the RFC section is not a proper fix and thus not an option to be merged. Instead, we should fix the IETF parser.

**Comment by Elchi3** [comment]
OK

**Pull request closed without merging**
