### PR TITLE
Add Octave Documentation

### PR DESCRIPTION
**Pull request by scherepn**
Add a scraper for the Octave documentation.

The documentation is licensed under a custom license, but it allows for both commercial redistribution and modifications, so it should be fine to include.

The prism library used by devdocs will need to be updated to support this language's syntax highlighting.

### CODE REVIEW

**Comment by jmerle** [comment]
Prism.js doesn't support Octave ([supported languages](https://prismjs.com/index.html#languages-list)), so code blocks will not be syntax highlighted.

**Comment by j-f1** [comment]
Here’s the docs for creating a new Prism language, if you’re willing to do so: https://prismjs.com/extending.html#language-definitions

**Comment by scherepn** [comment]
Octave is a Free Software replacement for MATLAB, a proprietary language. Prism supports MATLAB and they're close enough that for the purposes of syntax highlighting, everything should mostly work.

**Comment by scherepn** [comment]
I noticed pull #986 was merged, so I added `get_latest_version` for Octave.

**Comment by jmerle** [comment]
Thanks! Deployed to [https://devdocs.io/octave/](https://devdocs.io/octave/).

**Comment by scherepn** [comment]
Will there be an update to the news/changelog about this addition?

https://devdocs.io/news

**Comment by jmerle** [comment]
It will be after I merged the Django and Trio docs.

**Comment by scherepn** [comment]
:+1:

**Pull request merged**
