### PR TITLE
Upgrade Ruby and gems

### PR DESCRIPTION
**Pull request by larouxn**
- Upgrade Ruby to [2.6.3](https://www.ruby-lang.org/en/news/2019/04/17/ruby-2-6-3-released/) (mostly bug fixes since [2.6.0](https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/))
- Incidentally upgrade a few gems

### CODE REVIEW

**Comment by j-f1** [comment]
Do the security vulnerabilities affect DevDocs since it doesn’t use Rails?

**Comment by larouxn** [comment]
Ah good point. I suppose not.

**Comment by taylorthurlow** [comment]
Would be awesome to get this one merged!

**Comment by larouxn** [comment]
As it's been a few weeks, I ran another `bundle update` to grab `activesupport` 5.2.3 and such.

**Comment by jmgarnier** [comment]
would be nice to get this PR merged :)

**Comment by larouxn** [comment]
Further updated this PR to bring us up to Ruby 2.6.3 and ran another `bundle update`. ⛵️ 🙏

**Comment by WA9ACE** [comment]
Is there anything preventing this from being merged and deployed?

**Comment by jmerle** [comment]
Code-wise no, but only Quincy has access to all the services required to run a full deployment at the moment and he is currently busy with other freeCodeCamp projects. See the latest few comments in the [Gitter channel](https://gitter.im/FreeCodeCamp/DevDocs) for more information.

**Comment by larouxn** [comment]
As it's been quite some time agan, I ran another `bundle update`. Mostly minor gem bumps.

**Comment by jmerle** [comment]
Kinda outside the scope of this PR, but I modified the Travis configuration anyways to make builds ~30 seconds faster by not downloading documentation when running `gem update --system`. Also updated Bundler to 2.x which doesn't seem to cause problems.

Thanks for your PR!

**Comment by taylorthurlow** [comment]
Hi ho! What a momentus day this is, Ruby 2.6 in my devdocs.io!

**Pull request merged**
