### PR TITLE
update php documentation (7.4.5)

### PR DESCRIPTION
**Pull request by jhdxr**
If you're updating an existing documentation to it's latest version, please ensure that you have:

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Comment by rickmacgillis** [comment]
I was just about to write an update for the PHP versions, but it seems that @jhdxr beat me to it, so that saves me some work.

Any chance someone can inspect his PR and merge it for us?

**Comment by jhdxr** [comment]
Hi @rickmacgillis 
> I just noticed that he removed the old version of the docs instead of adding a versions list. I'm going to have a go at it to make it so people can select which version(s) they want to install.
The reason I do so is it's how devdocs deal with php document now, and so does php.net. 

Since php document is basicly a reference for all the php functions. It indicates since when functions are avaliable or removed rather than providing documentation for different php versions.

**Comment by zicjin** [comment]
@jhdxr May I ask this PR support from https://www.php.net/distributions /manual/php_manual_en.tar.gz Download the offline documentation? I download the offline document and execute "thor docs:generate php", why do I get a lot of code that doesn't match the actual html structure? clear_html.rb:16 at_css('.manualnavbar') Object Non-existent.

**Review by simon04 — CHANGES_REQUESTED** [review]
I cannot build the docs after downloading the 2020-11-13 version from php.net via `mkdir -p docs/php/; curl https://www.php.net/distributions/manual/php_manual_en.tar.gz | tar xz --strip-components=1 --directory=docs/php/`

**Comment by jhdxr** [comment]
Sorry I'm going to abandon this PR. It seems the php manual updated its css and dom, so besides the contents changes (including new pages, excluding removed pages, like what this PR does), the more important thing is to update the filters to make it compatibile with the latest manual. I don't have enough time to check and implement those changes currently. Maybe @rickmacgillis  can help on this? If you are still interested in it.

**Comment by simon04** [comment]
> If you are still interested in it.

If the question was directed to the @freeCodeCamp/devdocs team: yes, definitively!

**Comment by jhdxr** [comment]
@simon04 Really glad to hear that. Hope to see it get updated soon. Thanks.

**Pull request closed without merging**
