### PR TITLE
Update Npm to 7.1.2

### PR DESCRIPTION
**Pull request by MasterEnoc**
- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Review by simon04 — COMMENTED** [review]
The https://devdocs.io/npm/files/package.json section is missing. Intended?

**Comment by MasterEnoc** [comment]
Yes, I did not add 'package.json' section since it does not add any API information and does not contain configuration variables like 'Config' does.

**Comment by simon04** [comment]
In the past, I often found myself to lookup the specification of certain `package.json` keys. Therefore I would keep it included…

**Comment by MasterEnoc** [comment]
'package.json' section added.

**Review by simon04 — APPROVED** [review]
Thank you!

**Pull request merged**
