### PR TITLE
Update crystal 0.35

### PR DESCRIPTION
**Pull request by Daniel-Worrall**
If you're updating an existing documentation to it's latest version, please ensure that you have:

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

E: 0.34 manual checks done, 0.35 releases soon

### CODE REVIEW

**Comment by jhass** [comment]
Meanwhile 0.34 was released

ref #1211

**Comment by Daniel-Worrall** [comment]
Will update soon

**Comment by Daniel-Worrall** [comment]
Updated to use 0.33 and 0.34. Done all manual checks

**Comment by carlhoerberg** [comment]
0.35 is out

**Comment by simon04** [comment]
There have been so many releases in the past year that I've decided to only provide the latest one…

**Review by simon04 — APPROVED** [review]

**Pull request merged**
