### PR TITLE
Bump homebrew to 2.0.2 (latest version)

### PR DESCRIPTION
**Pull request by szb512**
[ x] Tested the scraper on a local copy of DevDocs
[x ] Ensured that the docs are styled similarly to other docs on DevDocs

This will pretty much bump homebrew to 2.0.2.

### CODE REVIEW

**Comment by szb512** [comment]
Did I forget to mention that the process uses homebrew to upgrade?

**Comment by szb512** [comment]
Also it will move docker from 18.03 to 18.06.

**Comment by j-f1** [comment]
Please upgrade the original source files instead of creating new ones.

**Comment by szb512** [comment]
What files do I need to edit then?

**Comment by jmerle** [comment]
Requesting @j-f1's opinion on this. I don't think we need new PR's for minor and patch releases when there are already open PR's for the major versions (Homebrew 2.0.2 at #978 and Docker 18.03 at #976) and when the documentation structure hasn't changed. Most PR's will already be outdated by the time we can get them reviewed, so I think it is our responsibility as maintainer to ensure we update to the latest version when we merge a PR that updates a scraper. For that reason I'd vote to close this PR.

As to answer your question, you can look in the PR's I linked above to see the changes the contributors made.

**Pull request closed without merging**
