### PR TITLE
Update Ruby on Rails documentation (6.0.0)

### PR DESCRIPTION
**Pull request by crescentrose**
If you're updating an existing documentation to it's latest version, please ensure that you have:

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date and that the documentation's entry in the array in `about_tmpl.coffee` matches it's data in `self.attribution`
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [x] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

This is my first attempt at updating the docs, please tell me if I did something wrong! 😅

### CODE REVIEW

**Comment by crescentrose** [comment]
> You updated `options[:attribution]` without changing the `about_tmpl.coffee` file. Please don't check checkboxes in the PR template without actually doing what the item says, it's annoying.

Sorry, the `about_tmpl.coffee` file had `2017` as the copyright year instead of the latest year that the copyright was valid for in the `rails.rb` file so I assumed that there was a reason for it being like that. Probably a poor assumption on my end. I've changed that now.

**Comment by jmerle** [comment]
Thanks for solving the about_tmpl issue. Please mention such assumptions in the PR next time instead of just ticking the checkbox though.

I just tried scraping version 6.0.0 on your branch, but I'm wondering how you ran the scraper without seeing errors. These are the errors I get:

```
ERROR: https://user-images.githubusercontent.com/5355/28694528-16e69d0c-72f8-11e7-91a7-c0b8cfc90391.gif                                                                                                          
  NameError: uninitialized constant Docs::ImagesFilter::ImageOptim

  /home/jasper/Projects/devdocs/lib/docs/filters/core/images.rb:10:in `optimize_image_data'
  /home/jasper/Projects/devdocs/lib/docs/filters/core/images.rb:50:in `block (2 levels) in call'
  /home/jasper/Projects/devdocs/lib/docs/core/request.rb:27:in `block in run'
  /home/jasper/Projects/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /home/jasper/Projects/devdocs/lib/docs/core/request.rb:26:in `run'
  /home/jasper/Projects/devdocs/lib/docs/core/request.rb:13:in `run'
  /home/jasper/Projects/devdocs/lib/docs/filters/core/images.rb:36:in `block in call'
  /home/jasper/Projects/devdocs/lib/docs/filters/core/images.rb:21:in `call'
  /home/jasper/Projects/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /home/jasper/Projects/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:179:in `process_response'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:269:in `process_response'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:160:in `block in handle_response'
  /home/jasper/Projects/devdocs/lib/docs/core/instrumentable.rb:15:in `instrument'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:159:in `handle_response'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:77:in `block in build_pages'
  /home/jasper/Projects/devdocs/lib/docs/core/scrapers/file_scraper.rb:39:in `request_all'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:76:in `build_pages'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:241:in `fetch_internal_urls'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:232:in `with_internal_urls'
  /home/jasper/Projects/devdocs/lib/docs/core/scraper.rb:223:in `store_pages'
  /home/jasper/Projects/devdocs/lib/docs.rb:100:in `generate'
  /home/jasper/Projects/devdocs/lib/tasks/docs.thor:300:in `generate_doc'
  /home/jasper/Projects/devdocs/lib/tasks/docs.thor:106:in `generate'

ERROR: Failed to open file: /home/jasper/Projects/devdocs/docs/rails~6.0/ActionDispatch/www.example.com                                                                                                          
ERROR: Failed to open file: /home/jasper/Projects/devdocs/docs/rails~6.0/ActionDispatch/Http/www.rubyonrails.org                                                                                                 
ERROR: Failed to open file: /home/jasper/Projects/devdocs/docs/rails~6.0/ActionDispatch/Http/www.rubyonrails.co.uk                                                                                               
ERROR: Failed to open file: /home/jasper/Projects/devdocs/docs/rails~6.0/'TZ'                                                                                                                                    
ERROR: Failed to open file: /home/jasper/Projects/devdocs/docs/rails~6.0/active_record_migrations.html                                                                                                           
ERROR: Failed to open file: /home/jasper/Projects/devdocs/docs/rails~6.0/association_basics.html
```

The first error is probably caused by a commit I made yesterday and can be fixed by adding `require 'image_optim'` to the top of `lib/docs/filters/core/images.rb`, but I'm wondering how you managed to run the scraper without getting the `ERROR: Failed to open file` errors.

Could you please tell me how you generated the content in the `docs/rails~6.0` directory to make the scraping happen without errors? I followed the steps in the comments of the `rails.rb` file, but if you did something different, please update those comments to reflect the right way to generate the to-be-scraped files.

**Comment by swrobel** [comment]
@crescentrose are you still working on this? Having Rails 6 docs would be awesome!

**Comment by jmerle** [comment]
30 days have passed so I'm closing this PR. Feel free to create another PR in the future, but please don't tick the "Tested the changes locally to ensure" checkbox when you haven't tried it locally.

**Pull request closed without merging**
