### PR TITLE
Update Git to 2.46.0

### PR DESCRIPTION
**Pull request by adamchainz**
Release announcement: https://public-inbox.org/git/xmqqzfq0i0qa.fsf@gitster.g/

- [x] Updated the versions and releases in the scraper file
- [x] Ensured the license is up-to-date - changed back to GPL. #1068 changed to the license of the git-scm.com website, but the documentation is not hosted in that repository, instead in the `Documentation/` directory of the `git/git` repository: https://github.com/git/git/tree/master/Documentation . So this PR changes the license back to the GPL v2 per https://github.com/git/git/blob/master/COPYING .
- [x] Ensured the icons and the `SOURCE` file in <code>public/icons/*your_scraper_name*/</code> are up-to-date if the documentation has a custom icon
- [x] Ensured `self.links` contains up-to-date urls if `self.links` is defined
- [ ] Tested the changes locally to ensure:
  - The scraper still works without errors
  - The scraped documentation still looks consistent with the rest of DevDocs
  - The categorization of entries is still good

### CODE REVIEW

**Review by simon04 — APPROVED** [review]
Thank you!

**Comment by adamchainz** [comment]
Why did you undo my license fix? Did you read the PR description?

**Comment by simon04** [comment]
Thanks for reaching out again. No, I've overlooked the explanation in the middle of standard tickboxes. Fixed https://github.com/freeCodeCamp/devdocs/commit/892896c1d4d5c14ac2c8811f4984cf68b2d32b3f.

**Comment by adamchainz** [comment]
Ah, sorry for burying it there.

Thanks!

**Pull request merged**
